# Compose is used to link networks between 
# the different services (each service is in its own container)

version: "2"

services:
  hello: # host is hello
    build: src/helloservice
    image: helloapp:v1
    ports:
      - "8080:8080"
    labels:
      kompose.image-pull-policy: "Never"

  loadgen: # load generator
    build: src/loadgeneratorservice
    image: loadgenapp:v1
    ports:
      - "8081:8081"
    labels:
      kompose.image-pull-policy: "Never"