# Compose is used to link networks between 
# the different services (each service is in its own container)

version: "2"

services:
  hello: # host is hello
    build: src/helloservice
    image: us-central1-docker.pkg.dev/pixie2022f/hellorepo/helloapp:v1
    ports:
      - "8080:8080"

  loadgen: # load generator
    build: src/loadgeneratorservice
    image: us-central1-docker.pkg.dev/pixie2022f/hellorepo/loadgenapp:v1
    ports:
      - "8081:8081"
