apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: ./kompose convert --out kubectl-kompose.yaml --build local
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: hello
      name: hello
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: hello
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: ./kompose convert --out kubectl-kompose.yaml --build local
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: loadgen
      name: loadgen
    spec:
      ports:
        - name: "8081"
          port: 8081
          targetPort: 8081
      selector:
        io.kompose.service: loadgen
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: ./kompose convert --out kubectl-kompose.yaml --build local
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: hello
      name: hello
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: hello
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: ./kompose convert --out kubectl-kompose.yaml --build local
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.service: hello
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/pixie2022f/hellorepo/helloapp:v1
              name: hello
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: ./kompose convert --out kubectl-kompose.yaml --build local
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: loadgen
      name: loadgen
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: loadgen
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: ./kompose convert --out kubectl-kompose.yaml --build local
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.service: loadgen
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/pixie2022f/hellorepo/loadgenapp:v1
              name: loadgen
              ports:
                - containerPort: 8081
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

